name: E2E
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          python-version: "3.10"
      - name: Run tests
        run: poetry run make test-e2e
